const countries = {
    "as-IN": "Assamese",
    "bn-IN": "Bengali",
    "br-IN": "Bodo",
    "doi-IN": "Dogri",
    "gu-IN": "Gujarati",
    "hi-IN": "Hindi",
    "kn-IN": "Kannada",
    "ks-IN": "Kashmiri",
    "kok-IN": "Konkani",
    "mai-IN": "Maithili",
    "ml-IN": "Malayalam",
    "mr-IN": "Marathi",
    "mni-IN": "Meitei",
    "ne-IN": "Nepali",
    "or-IN": "Odia",
    "pa-IN": "Punjabi",
    "sa-IN": "Sanskrit",
    "sat-IN": "Santali",
    "sd-IN": "Sindhi",
    "ta-IN": "Tamil",
    "te-IN": "Telugu",
    "ur-IN": "Urdu",
};
